import { describe, expect, it } from 'vitest'

import { buildDdl } from '../electron/drivers/ddl.js'
import { mayWrite } from '../electron/drivers/statements.js'

const pgQuote = (name) => `"${String(name).replace(/"/g, '""')}"`
const myQuote = (name) => `\`${String(name).replace(/`/g, '``')}\``

const pgNode = { kind: 'table', path: { database: 'app', schema: 'public', table: 'users' } }
const myNode = { kind: 'table', path: { database: 'app', table: 'users' } }
const liteNode = { kind: 'table', path: { table: 'users' } }

describe('buildDdl', () => {
  it('adds a column with the engine\'s own wording', () => {
    const column = { name: 'age', type: 'integer', nullable: false, defaultExpression: '0' }

    expect(buildDdl('postgres', pgQuote, pgNode, { kind: 'addColumn', column }))
      .toEqual(['alter table "public"."users" add column "age" integer not null default 0;'])
    expect(buildDdl('mysql', myQuote, myNode, { kind: 'addColumn', column }))
      .toEqual(['alter table `app`.`users` add column `age` integer not null default 0;'])
    expect(buildDdl('sqlite', pgQuote, liteNode, { kind: 'addColumn', column }))
      .toEqual(['alter table "users" add column "age" integer not null default 0;'])
  })

  it('writes a Postgres column comment as its own statement', () => {
    expect(buildDdl('postgres', pgQuote, pgNode, { kind: 'addColumn', column: { name: 'note', type: 'text', comment: 'it\'s free' } }))
      .toEqual([
        'alter table "public"."users" add column "note" text;',
        'comment on column "public"."users"."note" is \'it\'\'s free\';',
      ])
  })

  it('alters a column in place on Postgres and MySQL, and refuses on SQLite', () => {
    expect(buildDdl('postgres', pgQuote, pgNode, { kind: 'alterColumn', name: 'age', type: 'bigint', nullable: true, defaultExpression: null }))
      .toEqual(['alter table "public"."users"\n  alter column "age" type bigint,\n  alter column "age" drop not null,\n  alter column "age" drop default;'])

    expect(buildDdl('mysql', myQuote, myNode, { kind: 'alterColumn', name: 'age', type: 'bigint', nullable: false }))
      .toEqual(['alter table `app`.`users` modify column `age` bigint not null;'])

    expect(() => buildDdl('sqlite', pgQuote, liteNode, { kind: 'alterColumn', name: 'age', type: 'bigint' })).toThrow(/SQLite/)
  })

  it('creates and drops indexes where each engine wants the name', () => {
    const create = { kind: 'createIndex', name: 'users_email', columns: ['email'], unique: true }
    expect(buildDdl('postgres', pgQuote, pgNode, create)).toEqual(['create unique index "users_email" on "public"."users" ("email");'])
    expect(buildDdl('mysql', myQuote, myNode, { kind: 'dropIndex', name: 'users_email' })).toEqual(['drop index `users_email` on `app`.`users`;'])
    expect(buildDdl('postgres', pgQuote, pgNode, { kind: 'dropIndex', name: 'users_email' })).toEqual(['drop index "public"."users_email";'])
    expect(buildDdl('sqlite', pgQuote, liteNode, { kind: 'dropIndex', name: 'users_email' })).toEqual(['drop index "users_email";'])
  })

  it('creates a table with an auto-increment key per engine', () => {
    const columns = [
      { name: 'id', type: 'integer', primaryKey: true, autoIncrement: true },
      { name: 'name', type: 'text', nullable: false },
    ]

    expect(buildDdl('postgres', pgQuote, pgNode, { kind: 'createTable', name: 'things', columns })).toEqual([
      'create table "public"."things" (\n  "id" integer generated by default as identity primary key,\n  "name" text not null\n);',
    ])
    expect(buildDdl('mysql', myQuote, myNode, { kind: 'createTable', name: 'things', columns })).toEqual([
      'create table `app`.`things` (\n  `id` integer not null auto_increment primary key,\n  `name` text not null\n);',
    ])
    expect(buildDdl('sqlite', pgQuote, liteNode, { kind: 'createTable', name: 'things', columns })).toEqual([
      'create table "things" (\n  "id" integer primary key autoincrement,\n  "name" text not null\n);',
    ])
  })

  it('declares a composite key after the columns', () => {
    const columns = [
      { name: 'a', type: 'int', primaryKey: true },
      { name: 'b', type: 'int', primaryKey: true },
    ]
    expect(buildDdl('postgres', pgQuote, pgNode, { kind: 'createTable', name: 'pairs', columns })).toEqual([
      'create table "public"."pairs" (\n  "a" int,\n  "b" int,\n  primary key ("a", "b")\n);',
    ])
  })

  it('renames tables and columns, and quotes names that need it', () => {
    expect(buildDdl('postgres', pgQuote, pgNode, { kind: 'renameTable', to: 'People "v2"' }))
      .toEqual(['alter table "public"."users" rename to "People ""v2""";'])
    expect(buildDdl('sqlite', pgQuote, liteNode, { kind: 'renameColumn', name: 'name', to: 'full_name' }))
      .toEqual(['alter table "users" rename column "name" to "full_name";'])
  })

  it('refuses an empty name', () => {
    expect(() => buildDdl('postgres', pgQuote, pgNode, { kind: 'dropColumn', name: ' ' })).toThrow(/required/)
  })
})

describe('mayWrite', () => {
  it('lets reads through and flags everything else', () => {
    expect(mayWrite('select 1')).toBe(false)
    expect(mayWrite('  -- note\n  WITH x AS (select 1) select * from x')).toBe(false)
    expect(mayWrite('explain analyze select 1')).toBe(false)
    expect(mayWrite('update t set a = 1')).toBe(true)
    expect(mayWrite('DELETE FROM t')).toBe(true)
    expect(mayWrite('alter table t add column c int')).toBe(true)
    expect(mayWrite('(select 1)')).toBe(true)
  })
})
