/**
 * Structure changes, spelled per engine.
 *
 * A column added, an index dropped, a table renamed: the intent is the same
 * everywhere and the words differ in the details — how a default is written,
 * whether a column's type can be changed at all, where the index name goes
 * in a DROP. Each engine's spelling lives here, behind one function, so the
 * structure view builds one operation and the driver decides the SQL.
 *
 * Names are quoted; types and default expressions are written as typed.
 * They are the user's own DDL, and the engine is the right judge of them.
 */

/** A pair of quoting functions and a qualified table name, per engine. */
function dialectFor(engine, quoteIdent, node) {
  const table = engine === 'postgres'
    ? `${quoteIdent(node.path.schema)}.${quoteIdent(node.path.table)}`
    : engine === 'mysql'
      ? `${quoteIdent(node.path.database)}.${quoteIdent(node.path.table)}`
      : quoteIdent(node.path.table)

  /** A new table beside this one: same schema or database, its own name. */
  const sibling = (name) => (engine === 'postgres'
    ? `${quoteIdent(node.path.schema)}.${quoteIdent(name)}`
    : engine === 'mysql'
      ? `${quoteIdent(node.path.database)}.${quoteIdent(name)}`
      : quoteIdent(name))

  return { table, sibling }
}

function literal(text) {
  return `'${String(text).replace(/'/g, "''")}'`
}

function need(value, what) {
  const text = typeof value === 'string' ? value.trim() : ''
  if (!text) throw new Error(`${what} is required.`)
  return text
}

/** One column of a CREATE TABLE or ADD COLUMN, in the engine's words. */
function columnDefinition(engine, quoteIdent, column, { inline = true } = {}) {
  const name = quoteIdent(need(column.name, 'A column name'))
  let type = need(column.type, `A type for ${column.name}`)
  const parts = [name]

  if (column.autoIncrement) {
    if (engine === 'postgres') {
      parts.push(type, 'generated by default as identity')
    }
    else if (engine === 'mysql') {
      parts.push(type, 'not null', 'auto_increment')
    }
    else {
      // SQLite's only auto-increment is the rowid alias, which must be spelled
      // exactly `integer primary key`.
      type = 'integer'
      parts.push(type, 'primary key autoincrement')
    }
  }
  else {
    parts.push(type)
  }

  if (!column.autoIncrement || engine === 'postgres') {
    if (column.nullable === false && !(engine === 'sqlite' && column.autoIncrement)) parts.push('not null')
  }

  if (column.defaultExpression !== undefined && column.defaultExpression !== null && String(column.defaultExpression).trim() !== '') {
    parts.push(`default ${String(column.defaultExpression).trim()}`)
  }

  if (inline && column.primaryKey && !(engine === 'sqlite' && column.autoIncrement)) parts.push('primary key')

  if (engine === 'mysql' && column.comment) parts.push(`comment ${literal(column.comment)}`)

  return parts.join(' ')
}

/**
 * @param {'postgres' | 'mysql' | 'sqlite'} engine
 * @param {(name: string) => string} quoteIdent
 * @param {object} node  The table the operation is about; for createTable, where the new table goes.
 * @param {object} operation  A `DdlOperation`; see shared/db-types.ts.
 * @returns {string[]}  The statements, in order, each ending in a semicolon.
 */
export function buildDdl(engine, quoteIdent, node, operation) {
  const { table, sibling } = dialectFor(engine, quoteIdent, node)

  switch (operation.kind) {
    case 'createTable': {
      const name = need(operation.name, 'A table name')
      const columns = Array.isArray(operation.columns) ? operation.columns : []
      if (!columns.length) throw new Error('A table needs at least one column.')

      const keys = columns.filter((column) => column.primaryKey)
      // A composite key is declared once, after the columns; a single one
      // reads better inline. SQLite's autoincrement column is its own key.
      const compositeKey = keys.length > 1 && !(engine === 'sqlite' && keys.some((column) => column.autoIncrement))

      const lines = columns.map((column) => columnDefinition(engine, quoteIdent, column, { inline: !compositeKey }))
      if (compositeKey) lines.push(`primary key (${keys.map((column) => quoteIdent(column.name)).join(', ')})`)

      const statements = [`create table ${sibling(name)} (\n${lines.map((line) => `  ${line}`).join(',\n')}\n);`]

      if (engine === 'postgres') {
        for (const column of columns) {
          if (column.comment) {
            statements.push(`comment on column ${sibling(name)}.${quoteIdent(column.name)} is ${literal(column.comment)};`)
          }
        }
      }

      return statements
    }

    case 'renameTable':
      return [`alter table ${table} rename to ${quoteIdent(need(operation.to, 'The new name'))};`]

    case 'dropTable':
      return [`drop table ${table};`]

    case 'addColumn': {
      const column = operation.column ?? {}
      if (column.autoIncrement && engine === 'sqlite') {
        throw new Error('SQLite cannot add an autoincrement column to an existing table.')
      }

      const statements = [`alter table ${table} add column ${columnDefinition(engine, quoteIdent, column, { inline: false })};`]

      if (engine === 'postgres' && column.comment) {
        statements.push(`comment on column ${table}.${quoteIdent(column.name)} is ${literal(column.comment)};`)
      }

      return statements
    }

    case 'dropColumn':
      return [`alter table ${table} drop column ${quoteIdent(need(operation.name, 'The column'))};`]

    case 'renameColumn':
      return [
        `alter table ${table} rename column ${quoteIdent(need(operation.name, 'The column'))} to ${quoteIdent(need(operation.to, 'The new name'))};`,
      ]

    case 'alterColumn': {
      const name = quoteIdent(need(operation.name, 'The column'))

      if (engine === 'sqlite') {
        throw new Error(
          'SQLite cannot change a column\'s type, nullability or default. Create a new column and copy the data, or rebuild the table.',
        )
      }

      if (engine === 'mysql') {
        // MODIFY rewrites the whole definition, so every part has to be said
        // again: a type alone would silently make the column nullable.
        const type = need(operation.type, 'The column type')
        const parts = [type, operation.nullable === false ? 'not null' : 'null']
        if (typeof operation.defaultExpression === 'string' && operation.defaultExpression.trim()) {
          parts.push(`default ${operation.defaultExpression.trim()}`)
        }
        return [`alter table ${table} modify column ${name} ${parts.join(' ')};`]
      }

      const clauses = []
      if (typeof operation.type === 'string' && operation.type.trim()) {
        clauses.push(`alter column ${name} type ${operation.type.trim()}`)
      }
      if (typeof operation.nullable === 'boolean') {
        clauses.push(`alter column ${name} ${operation.nullable ? 'drop not null' : 'set not null'}`)
      }
      if (operation.defaultExpression === null) {
        clauses.push(`alter column ${name} drop default`)
      }
      else if (typeof operation.defaultExpression === 'string' && operation.defaultExpression.trim()) {
        clauses.push(`alter column ${name} set default ${operation.defaultExpression.trim()}`)
      }

      if (!clauses.length) throw new Error('Nothing about the column was changed.')
      return [`alter table ${table}\n  ${clauses.join(',\n  ')};`]
    }

    case 'createIndex': {
      const name = need(operation.name, 'An index name')
      const columns = (Array.isArray(operation.columns) ? operation.columns : []).filter((column) => typeof column === 'string' && column)
      if (!columns.length) throw new Error('An index needs at least one column.')

      const unique = operation.unique ? 'unique ' : ''
      const list = columns.map((column) => quoteIdent(column)).join(', ')

      // Postgres names an index within the table's schema; the CREATE takes
      // the bare name and puts it there. SQLite the same, MySQL per table.
      return [`create ${unique}index ${quoteIdent(name)} on ${table} (${list});`]
    }

    case 'dropIndex': {
      const name = need(operation.name, 'The index')

      if (engine === 'mysql') return [`drop index ${quoteIdent(name)} on ${table};`]
      if (engine === 'postgres') return [`drop index ${quoteIdent(node.path.schema)}.${quoteIdent(name)};`]
      return [`drop index ${quoteIdent(name)};`]
    }

    default:
      throw new Error(`Unknown structure change "${operation?.kind}".`)
  }
}
