import { once } from 'node:events'

import pg from 'pg'
import QueryStream from 'pg-query-stream'

import { assertOneRow, buildStatements, literalFactory, previewOf } from './changes.js'
import { buildSnapshot, groupRelations, SCHEMA_COLUMN_LIMIT } from './introspection.js'
import {
  describePostgresError,
  describePostgresQueryError,
  explainConnectionError,
  explainQueryError,
} from './errors.js'
import { buildDdl as buildDdlStatements } from './ddl.js'
import { isRowProducing } from './statements.js'
import { tlsOptions } from './tls.js'
import { createRowSink } from './values.js'

const { Client, Pool } = pg

/**
 * Rows fetched per round trip while a result is streamed. A result the
 * renderer is drawing as it arrives asks for a small first batch instead, so
 * the first screen is not waiting on the five hundredth row.
 */
const STREAM_BATCH_SIZE = 500
const FIRST_STREAM_BATCH_SIZE = 50

// `numeric` and `int8` arrive as strings by default, which is what we want:
// precision survives the trip and the column's type name still tells the grid
// how to align it.

/**
 * Dates and times stay strings too, exactly as the server formatted them.
 *
 * pg otherwise builds a JS Date, which is wrong twice over: a `date` becomes
 * local midnight and comes back a day early once it is serialized in a zone
 * behind UTC, and a `timestamptz` loses the offset the server sent. As text,
 * what the grid shows — and what an edit sends back — is what the column holds.
 */
for (const oid of [
  1082, // date
  1083, // time
  1114, // timestamp
  1184, // timestamptz
  1266, // timetz
]) {
  pg.types.setTypeParser(oid, (value) => value)
}

function quoteIdent(name) {
  return `"${String(name).replace(/"/g, '""')}"`
}

function quoteLiteral(text) {
  return `'${String(text).replace(/'/g, "''")}'`
}

/** What COMMENT ON calls each kind of relation. */
const RELATION_KEYWORD = { v: 'view', m: 'materialized view' }

/**
 * Reads a trigger's timing and events out of `pg_trigger.tgtype`, a bit set:
 * 2 is BEFORE and 64 INSTEAD OF (neither is AFTER), then 4, 8, 16 and 32 are
 * INSERT, DELETE, UPDATE and TRUNCATE. Worded the way a CREATE TRIGGER
 * would be — `before insert or update` — which is what the explorer shows.
 */
function triggerTiming(tgtype) {
  const bits = Number(tgtype)
  const timing = bits & 64 ? 'instead of' : bits & 2 ? 'before' : 'after'

  const events = [
    [4, 'insert'],
    [16, 'update'],
    [8, 'delete'],
    [32, 'truncate'],
  ]
    .filter(([bit]) => bits & bit)
    .map(([, event]) => event)

  return `${timing} ${events.join(' or ')}`
}

/**
 * Writes the CREATE statement for a relation out of the catalog rows
 * `structure` read: a view is the server's own rendering of its query, a table
 * is its columns and constraints, then the indexes that back no constraint and
 * the comments anyone left.
 */
function buildDdl(node, relation, columns, constraints, indexes) {
  const qualified = `${quoteIdent(node.path.schema)}.${quoteIdent(node.path.table)}`
  const keyword = RELATION_KEYWORD[relation.relkind] ?? 'table'
  const lines = []

  if (relation.viewdef != null) {
    // pg_get_viewdef ends its text with a semicolon of its own.
    const query = relation.viewdef.trim()
    lines.push(`create ${keyword} ${qualified} as\n${query}${query.endsWith(';') ? '' : ';'}`)
  }
  else {
    const body = [
      ...columns.map((column) => {
        const parts = [quoteIdent(column.attname), column.type]

        if (column.attnotnull) parts.push('not null')

        if (column.attgenerated === 's') parts.push(`generated always as (${column.expression}) stored`)
        else if (column.expression != null) parts.push(`default ${column.expression}`)

        if (column.attidentity === 'a') parts.push('generated always as identity')
        if (column.attidentity === 'd') parts.push('generated by default as identity')

        return parts.join(' ')
      }),
      ...constraints.map((constraint) => `constraint ${quoteIdent(constraint.conname)} ${constraint.definition}`),
    ]

    lines.push(body.length
      ? `create table ${qualified} (\n${body.map((line) => `  ${line}`).join(',\n')}\n);`
      : `create table ${qualified} ();`)
  }

  // A primary key or unique constraint already declared its index above.
  const backing = new Set(constraints.filter((c) => c.conindid != null).map((c) => String(c.conindid)))

  for (const index of indexes) {
    if (backing.has(String(index.oid)) || !index.definition) continue
    lines.push(`${index.definition};`)
  }

  if (relation.comment != null) {
    lines.push(`comment on ${keyword} ${qualified} is ${quoteLiteral(relation.comment)};`)
  }

  for (const column of columns) {
    if (column.comment == null) continue
    lines.push(`comment on column ${qualified}.${quoteIdent(column.attname)} is ${quoteLiteral(column.comment)};`)
  }

  return lines.join('\n')
}

/**
 * Postgres reaches exactly one database per connection, so expanding a database
 * other than the profile's opens a second pool. They are cached per session and
 * closed together with it.
 */
function createPoolFactory(profile, secret, ssl) {
  const pools = new Map()

  /** Which database a request lands in when the caller names none. */
  function poolKey(database) {
    return database ?? profile.database ?? 'postgres'
  }

  function poolFor(database) {
    const key = poolKey(database)

    if (!pools.has(key)) {
      pools.set(key, new Pool({
        host: profile.host,
        port: profile.port ?? 5432,
        user: profile.username,
        password: secret,
        database: key,
        ssl,
        max: 4,
        connectionTimeoutMillis: 10_000,
        application_name: 'DBison',
      }))
    }

    return pools.get(key)
  }

  async function closeAll() {
    await Promise.allSettled([...pools.values()].map((pool) => pool.end()))
    pools.clear()
  }

  return { poolKey, poolFor, closeAll }
}

/**
 * Maps result field OIDs to the type names shown in column headers.
 *
 * OIDs are assigned per database, so a domain or enum in one is a different
 * number in the next: each database gets its own map, read once and kept.
 */
function createTypeNames() {
  const byDatabase = new Map()

  return function typeNamesFor(key, pool) {
    if (!byDatabase.has(key)) {
      byDatabase.set(
        key,
        pool.query('select oid, typname from pg_catalog.pg_type')
          .then(({ rows }) => new Map(rows.map((row) => [Number(row.oid), row.typname])))
          // A failed read must not stick: the next statement should try again.
          .catch((error) => {
            byDatabase.delete(key)
            throw error
          }),
      )
    }

    return byDatabase.get(key)
  }
}

/**
 * Runs a statement the plain way: the whole reply is fetched, then cut to the
 * cap. This is the path for everything a cursor cannot do — DML, DDL, session
 * settings, and a script of several statements, which the simple protocol
 * runs in one go.
 */
async function fetchStatement(client, sql, maxRows, sink) {
  const started = performance.now()
  const raw = await client.query({ text: sql, rowMode: 'array' })
  const durationMs = Math.round(performance.now() - started)

  // A multi-statement script yields one result per statement; the grid shows
  // the last one that produced rows, which is what a client expects.
  const results = Array.isArray(raw) ? raw : [raw]
  const last = [...results].reverse().find((r) => r.fields?.length) ?? results.at(-1)

  // The reply is already whole, so a streaming caller gets its rows in one
  // go: what the contract promises is the shape, not the pacing.
  sink.describe(last.fields ?? [])
  for (const row of last.rows.slice(0, maxRows)) sink.push(row)

  return {
    ...sink.finish(),
    truncated: last.rows.length > maxRows,
    command: last.command,
    affected: last.rowCount,
    statements: results.length,
    durationMs,
  }
}

/**
 * The extended protocol, which a cursor speaks, prepares the text as one
 * statement and refuses a script with 42601 before running any of it. That
 * refusal — a syntax error, no columns described yet, a semicolon in the text
 * — is the one case worth handing to the plain path, where the same script
 * has always worked. A single statement with a genuine syntax error meets the
 * same test and is simply parsed a second time, to the same error.
 */
function refusedAsScript(error, stream, sql) {
  return error?.code === '42601' && !stream._result.fields.length && sql.includes(';')
}

/**
 * Runs a row-producing statement through a cursor, reading only as far as the
 * display cap.
 *
 * The cursor is driven by hand rather than read as the stream it comes
 * wrapped in. The stream reports a failure only once its portal is closed,
 * and a connection that drops mid-result never confirms that close, so a
 * reader waiting on the stream would wait forever; a plain read rejects the
 * moment the client learns the connection is gone, and the close below is
 * raced against that same news.
 *
 * Rows come a batch at a time and the loop stops one past the cap: that row
 * proves the result was longer without fetching the rest of it. Closing the
 * cursor then closes the portal on the server, so a `select * from` over a
 * huge table costs one batch past the cap and no more.
 */
async function streamStatement(client, sql, maxRows, sink, { streaming }) {
  const started = performance.now()
  const stream = new QueryStream(sql, [], { rowMode: 'array', batchSize: STREAM_BATCH_SIZE })
  const { cursor } = stream

  // Armed before the statement is sent, so an end that arrives while a batch
  // is in flight is not missed; the listener is dropped on the way out.
  const settled = new AbortController()
  const lost = once(client, 'end', { signal: settled.signal }).catch(() => {})

  client.query(stream)

  let described = false
  let truncated = false
  let refused = false
  let durationMs

  try {
    while (!truncated) {
      // Only the very first read of a streamed result is small: once the
      // renderer has something to draw, round trips are the cost to cut.
      const asked = streaming && sink.count === 0 ? FIRST_STREAM_BATCH_SIZE : STREAM_BATCH_SIZE
      const batch = await cursor.read(asked)

      // The row description precedes the first row on the wire, so it is on
      // the result by the time the first read resolves, rows or none.
      if (!described) {
        sink.describe(stream._result.fields)
        described = true
      }

      for (const row of batch) {
        if (sink.count === maxRows) {
          truncated = true
          break
        }

        sink.push(row)
      }

      // Rows the renderer could be drawing while the next batch is fetched.
      sink.flush()

      // A portal hands back fewer rows than asked for only when it has run
      // to its end, so a short batch is the last one.
      if (batch.length < asked) break
    }

    // Taken before the close below: what the user waited for was the rows.
    durationMs = Math.round(performance.now() - started)
  }
  catch (error) {
    if (!refusedAsScript(error, stream, sql)) throw error
    refused = true
  }
  finally {
    // The client is busy until the server confirms the close, and must not
    // be handed back before then. A connection that dropped meanwhile would
    // never confirm anything, which is what `lost` is for.
    await Promise.race([cursor.close(), lost])
    settled.abort()
  }

  // Nothing ran and the client is idle again, so the script can be handed to
  // the path that runs it whole.
  if (refused) return fetchStatement(client, sql, maxRows, sink)

  // The command tag arrives only when the portal runs to its end, so a
  // truncated result has none; `affected` is the count of a data-modifying
  // CTE that produced no rows.
  const result = stream._result

  return {
    ...sink.finish(),
    truncated,
    command: result.command ?? undefined,
    affected: result.rowCount,
    statements: 1,
    durationMs,
  }
}

/** Shapes what either statement path produced into what the grid expects. */
function toResult(outcome) {
  return {
    columns: outcome.columns,
    // Empty when the rows went out in batches instead; `rowCount` is then
    // how many did. Either way it is what the grid received, not what the
    // statement produced, and `truncated` says whether more existed. See
    // shared/db-types.ts.
    rows: outcome.rows,
    rowCount: outcome.rowCount,
    streamed: outcome.streamed,
    truncated: outcome.truncated,
    // `command` is set for every statement that ran to completion; `affected`
    // is the count it reported, which means something only for DML.
    affectedRows: ['INSERT', 'UPDATE', 'DELETE'].includes(outcome.command)
      ? outcome.affected ?? 0
      : undefined,
    command: outcome.command,
    durationMs: outcome.durationMs,
    statements: outcome.statements,
  }
}

async function open(profile, secret) {
  // Read before any pool exists, so a certificate path that cannot be read
  // fails the open — and the connection dialog's Test — with a clear message.
  const ssl = tlsOptions(profile)
  const { poolKey, poolFor, closeAll } = createPoolFactory(profile, secret, ssl)
  const typeNamesFor = createTypeNames()
  const pool = poolFor(profile.database)

  let versionResult

  try {
    versionResult = await pool.query('select version() as version, current_database() as db')
    // Reading the catalog now both warms the cache and proves the handshake
    // reached a database we can actually introspect.
    await typeNamesFor(poolKey(profile.database), pool)
  }
  catch (error) {
    // Pools opened before the failure would otherwise keep retrying in the
    // background for a connection the user has already been told about.
    await closeAll()

    throw explainConnectionError(
      error,
      { ...profile, hasPassword: Boolean(secret) },
      describePostgresError,
    )
  }

  /**
   * Postgres cancels out of band: the request must arrive on a connection other
   * than the one that is busy. `pg_cancel_backend` does that over plain SQL,
   * and a user may always cancel their own backends.
   */
  async function cancelBackend(processId) {
    const canceller = new Client({
      host: profile.host,
      port: profile.port ?? 5432,
      user: profile.username,
      password: secret,
      database: profile.database ?? 'postgres',
      ssl,
      connectionTimeoutMillis: 5_000,
      application_name: 'DBison (cancel)',
    })

    try {
      await canceller.connect()
      await canceller.query('select pg_cancel_backend($1)', [processId])
    }
    finally {
      await canceller.end().catch(() => {})
    }
  }

  /**
   * Pooled clients pass between query tabs, so the search path is set on
   * every checkout rather than only when a schema was chosen: what the
   * previous statement left behind must not decide where this one looks.
   */
  function setSearchPath(client, schema) {
    return client.query(schema ? `set search_path to ${quoteIdent(schema)}` : 'reset search_path')
  }

  /**
   * Runs one statement on a client somebody else checked out — a pooled one
   * for the length of a query, or the one a transaction keeps. Which path the
   * statement takes is decided by its first keyword; see statements.js.
   *
   * `database` names the pool the client came from, which is where the type
   * names for its columns live. `onRows`, when given, receives the rows in
   * batches as they arrive instead of their coming back on the result.
   */
  async function runOnClient(client, sql, { maxRows, signal, database, onRows, binary }) {
    // Captured before the statement starts: after cancellation the client is
    // released and this would no longer be readable.
    const processId = client.processID
    const onAbort = () => { cancelBackend(processId).catch(() => {}) }
    signal?.addEventListener('abort', onAbort, { once: true })

    try {
      // Resolved before the statement rather than after it: a streamed result
      // names its columns on the first batch, which needs the type names then.
      const typeNames = await typeNamesFor(poolKey(database), poolFor(database))

      const sink = createRowSink({
        onRows,
        binary,
        columnsOf: (fields) => fields.map((field) => ({
          name: field.name,
          type: typeNames.get(field.dataTypeID) ?? `oid:${field.dataTypeID}`,
        })),
      })

      const outcome = isRowProducing(sql)
        ? await streamStatement(client, sql, maxRows, sink, { streaming: Boolean(onRows) })
        : await fetchStatement(client, sql, maxRows, sink)

      return toResult(outcome)
    }
    catch (error) {
      // 57014 is query_canceled: ours if we asked, otherwise the server's own
      // statement_timeout, which deserves the same calm wording either way.
      if (error?.code === '57014') throw Object.assign(new Error('Query cancelled.'), { cancelled: true })
      throw explainQueryError(error, sql, describePostgresQueryError)
    }
    finally {
      signal?.removeEventListener('abort', onAbort)
    }
  }

  /**
   * Runs a statement in the database and schema the query tab is pointed at.
   * Postgres reaches one database per connection, so the database picks the
   * pool; the schema is a session setting on the client we check out.
   */
  async function query(sql, { maxRows, signal, database, schema, onRows, binary }) {
    const client = await poolFor(database).connect()

    try {
      await setSearchPath(client, schema).catch((error) => {
        throw explainQueryError(error, sql, describePostgresQueryError)
      })

      return await runOnClient(client, sql, { maxRows, signal, database, onRows, binary })
    }
    finally {
      client.release()
    }
  }

  /**
   * Opens a transaction on one client and keeps it checked out until the
   * transaction ends, so every statement sent with it sees the others' work.
   *
   * A statement that fails or is cancelled leaves the transaction aborted,
   * as the engine has it: later statements are refused until a rollback,
   * which still works. A commit or rollback that fails itself hands the
   * client back to the pool as broken rather than as reusable — whatever
   * state it is in, the next tab must not inherit it.
   */
  async function beginTransaction({ database, schema } = {}) {
    const client = await poolFor(database).connect()

    try {
      await setSearchPath(client, schema)
      await client.query('begin')
    }
    catch (error) {
      client.release(error)
      throw explainQueryError(error, 'begin', describePostgresQueryError)
    }

    // A client held for minutes can lose its server — a restart, a timeout —
    // and pg reports that as an 'error' event on the client itself; the pool
    // listens only while the client is idle, and with nobody listening the
    // event would bring the process down. Swallowed here, the next statement
    // on the client fails in the ordinary way and the rollback lets it go.
    const onLost = () => {}
    client.on('error', onLost)

    let ended = false

    async function end(statement) {
      if (ended) return
      ended = true

      try {
        await client.query(statement)
        client.release()
      }
      catch (error) {
        client.release(error)
        throw explainQueryError(error, statement, describePostgresQueryError)
      }
      finally {
        client.off('error', onLost)
      }
    }

    return {
      query: (sql, { maxRows, signal, onRows, binary }) =>
        runOnClient(client, sql, { maxRows, signal, database, onRows, binary }),
      commit: () => end('commit'),
      rollback: () => end('rollback'),
    }
  }

  async function listChildren(node) {
    switch (node.kind) {
      case 'connection': {
        const { rows } = await pool.query(
          `select datname,
                  pg_size_pretty(pg_database_size(datname)) as size
             from pg_database
            where not datistemplate
            order by datname`,
        )

        return rows.map((row) => ({
          kind: 'database',
          name: row.datname,
          detail: row.size,
          expandable: true,
          path: { database: row.datname },
        }))
      }

      case 'database': {
        const { rows } = await poolFor(node.path.database).query(
          `select nspname
             from pg_namespace
            where left(nspname, 3) <> 'pg_' and nspname <> 'information_schema'
            order by nspname`,
        )

        return rows.map((row) => ({
          kind: 'schema',
          name: row.nspname,
          expandable: true,
          path: { ...node.path, schema: row.nspname },
        }))
      }

      case 'schema': {
        const { rows } = await poolFor(node.path.database).query(
          `select c.relname,
                  c.relkind,
                  c.reltuples::bigint as estimate
             from pg_class c
             join pg_namespace n on n.oid = c.relnamespace
            where n.nspname = $1 and c.relkind in ('r', 'p', 'v', 'm', 'f')
            order by c.relname`,
          [node.path.schema],
        )

        return rows.map((row) => ({
          kind: ['v', 'm'].includes(row.relkind) ? 'view' : 'table',
          name: row.relname,
          // reltuples is a planner estimate and is -1 before the first ANALYZE.
          detail: Number(row.estimate) >= 0 ? `~${Number(row.estimate).toLocaleString()} rows` : undefined,
          expandable: true,
          path: { ...node.path, table: row.relname },
        }))
      }

      case 'table':
      case 'view': {
        const { rows } = await poolFor(node.path.database).query(
          `select a.attname,
                  format_type(a.atttypid, a.atttypmod) as type,
                  a.attnotnull,
                  coalesce(i.indisprimary, false) as is_primary,
                  -- Anything the server can fill in by itself: a DEFAULT, a
                  -- sequence behind a serial, or an identity column. The grid
                  -- offers those to a new row instead of demanding a value.
                  (a.atthasdef or a.attidentity <> '') as has_default,
                  -- The labels of an enum column, so the grid can offer them
                  -- instead of asking the user to remember them. Cast to text:
                  -- enumlabel is a name, and the driver has no reader for
                  -- name[] (oid 1003) — it would hand back the literal {a,b}
                  -- string, which a list of options reads as one per character.
                  (select array_agg(e.enumlabel::text order by e.enumsortorder)
                     from pg_enum e
                    where e.enumtypid = a.atttypid) as enum_values
             from pg_attribute a
             join pg_class c on c.oid = a.attrelid
             join pg_namespace n on n.oid = c.relnamespace
             left join pg_index i on i.indrelid = c.oid
                                 and a.attnum = any(i.indkey)
                                 and i.indisprimary
            where n.nspname = $1 and c.relname = $2 and a.attnum > 0 and not a.attisdropped
            order by a.attnum`,
          [node.path.schema, node.path.table],
        )

        return rows.map((row) => ({
          kind: 'column',
          name: row.attname,
          detail: `${row.type}${row.attnotnull ? ' not null' : ''}`,
          primaryKey: row.is_primary,
          nullable: !row.attnotnull,
          hasDefault: row.has_default,
          declaredType: row.type,
          enumValues: row.enum_values ?? undefined,
          expandable: false,
          path: { ...node.path, column: row.attname },
        }))
      }

      default:
        return []
    }
  }

  /**
   * Reads a whole database in four statements, for the editor's completions.
   *
   * The catalog is joined rather than walked: one row per column for every
   * table and view outside the system schemas, which is a single sequential
   * pass for the server and a single round trip for us. The alternative — the
   * per-node queries the navigator uses — would be one round trip per table.
   */
  async function schemaSnapshot({ database } = {}) {
    const target = poolKey(database)
    const databasePool = poolFor(database)

    const [namespaces, columns, relations, stats] = await Promise.all([
      databasePool.query(
        `select nspname
           from pg_namespace
          where left(nspname, 3) <> 'pg_' and nspname <> 'information_schema'
          order by nspname`,
      ),

      // The left joins keep a table whose columns have all been dropped in the
      // list; it is still a name worth completing. Ordering by table is what
      // makes the cap below cut whole tables off the end rather than half of
      // every one of them.
      databasePool.query(
        `select n.nspname as "schema",
                c.relname as "table",
                case when c.relkind in ('v', 'm') then 'view' else 'table' end as "kind",
                a.attname as "column",
                format_type(a.atttypid, a.atttypmod) as "type",
                not a.attnotnull as "nullable",
                coalesce(pk.indisprimary, false) as "primaryKey"
           from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on a.attrelid = c.oid
                                   and a.attnum > 0
                                   and not a.attisdropped
           left join pg_index pk on pk.indrelid = c.oid
                                and pk.indisprimary
                                and a.attnum = any(pk.indkey)
          where c.relkind in ('r', 'p', 'v', 'm', 'f')
            and n.nspname <> 'information_schema'
            and left(n.nspname, 3) <> 'pg_'
          order by n.nspname, c.relname, a.attnum
          limit $1`,
        [SCHEMA_COLUMN_LIMIT + 1],
      ),

      // A composite key comes back as one row per column pair. `with
      // ordinality` is what keeps the two halves in step: array_agg over a bare
      // unnest has no defined order to line them up by.
      databasePool.query(
        `select con.oid as "key",
                n.nspname as "schema",
                c.relname as "table",
                nf.nspname as "refSchema",
                cf.relname as "refTable",
                (select array_agg(a.attname::text order by k.ord)
                   from unnest(con.conkey) with ordinality as k(attnum, ord)
                   join pg_attribute a on a.attrelid = con.conrelid and a.attnum = k.attnum) as "columns",
                (select array_agg(a.attname::text order by k.ord)
                   from unnest(con.confkey) with ordinality as k(attnum, ord)
                   join pg_attribute a on a.attrelid = con.confrelid and a.attnum = k.attnum) as "refColumns"
           from pg_constraint con
           join pg_class c on c.oid = con.conrelid
           join pg_namespace n on n.oid = c.relnamespace
           join pg_class cf on cf.oid = con.confrelid
           join pg_namespace nf on nf.oid = cf.relnamespace
          where con.contype = 'f'
            and n.nspname <> 'information_schema'
            and left(n.nspname, 3) <> 'pg_'`,
      ),

      // One row per table rather than per column: pg_total_relation_size is a
      // function call, and the column query would make the server run it once
      // for every column of every table.
      databasePool.query(
        `select n.nspname as "schema",
                c.relname as "table",
                -- A plain view stores no rows, so its reltuples describes
                -- nothing; a materialized one does, and reports honestly.
                case when c.relkind = 'v' then null
                     else c.reltuples::bigint end as "rowEstimate",
                case when c.relkind = 'v' then null
                     else pg_total_relation_size(c.oid) end as "bytes",
                obj_description(c.oid, 'pg_class') as "comment"
           from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
          where c.relkind in ('r', 'p', 'v', 'm', 'f')
            and n.nspname <> 'information_schema'
            and left(n.nspname, 3) <> 'pg_'`,
      ),
    ])

    const truncated = columns.rows.length > SCHEMA_COLUMN_LIMIT

    return buildSnapshot({
      database: target,
      schemas: namespaces.rows.map((row) => row.nspname),
      pathOf: (schema, table) => ({ database: target, schema, table }),
      columns: truncated ? columns.rows.slice(0, SCHEMA_COLUMN_LIMIT) : columns.rows,
      // bigint arrives as a string from pg: it is wider than a JS number can
      // hold in general, though a row count never is.
      stats: stats.rows.map((row) => ({
        schema: row.schema,
        table: row.table,
        rowEstimate: row.rowEstimate == null ? undefined : Number(row.rowEstimate),
        bytes: row.bytes == null ? undefined : Number(row.bytes),
        comment: row.comment,
      })),
      // One row per key here, so the grouping only unwraps the arrays the
      // server built.
      relations: groupRelations(relations.rows.flatMap((row) =>
        (Array.isArray(row.columns) ? row.columns : []).map((column, index) => ({
          key: String(row.key),
          schema: row.schema,
          table: row.table,
          column,
          refSchema: row.refSchema,
          refTable: row.refTable,
          refColumn: Array.isArray(row.refColumns) ? row.refColumns[index] : undefined,
        })),
      )),
      truncated,
    })
  }

  /**
   * A table's indexes, and a CREATE statement rebuilt from the catalog.
   *
   * Postgres keeps no CREATE TABLE text: the catalog is the definition, and
   * psql's `\d` is a rendering of it rather than a stored script. The same is
   * done here from the pieces the server will print for us — a column's type,
   * its default, each constraint and each index all have a catalog function
   * that writes them back the way they were declared.
   */
  async function structure(node) {
    const databasePool = poolFor(node.path.database)
    const params = [node.path.schema, node.path.table]

    const [relation, columns, constraints, indexes] = await Promise.all([
      databasePool.query(
        `select c.relkind,
                obj_description(c.oid, 'pg_class') as comment,
                case when c.relkind in ('v', 'm') then pg_get_viewdef(c.oid, true) end as viewdef
           from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
          where n.nspname = $1 and c.relname = $2`,
        params,
      ),

      // The default is printed by the server from its parsed form, so a serial
      // shows as the nextval() it really is. A generated column keeps its
      // expression in the same place, told apart by attgenerated.
      databasePool.query(
        `select a.attname,
                format_type(a.atttypid, a.atttypmod) as type,
                a.attnotnull,
                a.attidentity,
                a.attgenerated,
                pg_get_expr(d.adbin, d.adrelid) as expression,
                col_description(c.oid, a.attnum) as comment
           from pg_attribute a
           join pg_class c on c.oid = a.attrelid
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
          where n.nspname = $1 and c.relname = $2 and a.attnum > 0 and not a.attisdropped
          order by a.attnum`,
        params,
      ),

      // conindid names the index a key or exclusion constraint is built on, so
      // that index is not listed a second time as a CREATE INDEX of its own.
      databasePool.query(
        `select con.conname,
                con.contype,
                case when con.contype in ('p', 'u', 'x') then con.conindid end as conindid,
                pg_get_constraintdef(con.oid, true) as definition
           from pg_constraint con
           join pg_class c on c.oid = con.conrelid
           join pg_namespace n on n.oid = c.relnamespace
          where n.nspname = $1 and c.relname = $2 and con.contype in ('p', 'u', 'f', 'c', 'x')
          order by con.contype = 'p' desc, con.conname`,
        params,
      ),

      // Key columns in index order, the way schemaSnapshot reads a constraint's.
      // An expression has no pg_attribute row — its indkey entry is 0 — so the
      // server prints that one column of the index definition in its place.
      databasePool.query(
        `select i.relname as name,
                ix.indexrelid as oid,
                ix.indisunique as "unique",
                ix.indisprimary as "primary",
                pg_get_indexdef(ix.indexrelid) as definition,
                (select array_agg(
                          coalesce(a.attname::text, pg_get_indexdef(ix.indexrelid, k.ord::int, true))
                          order by k.ord)
                   from unnest(ix.indkey::int2[]) with ordinality as k(attnum, ord)
                   left join pg_attribute a on a.attrelid = ix.indrelid and a.attnum = k.attnum) as columns
           from pg_index ix
           join pg_class i on i.oid = ix.indexrelid
           join pg_class c on c.oid = ix.indrelid
           join pg_namespace n on n.oid = c.relnamespace
          where n.nspname = $1 and c.relname = $2
          order by ix.indisprimary desc, i.relname`,
        params,
      ),
    ])

    const target = relation.rows[0]
    if (!target) throw new Error(`No table or view named ${node.path.schema}.${node.path.table}.`)

    return {
      indexes: indexes.rows.map((row) => ({
        name: row.name,
        columns: Array.isArray(row.columns) ? row.columns : [],
        unique: row.unique,
        primary: row.primary,
        definition: row.definition,
      })),
      ddl: buildDdl(node, target, columns.rows, constraints.rows, indexes.rows),
      ddlNote: 'Rebuilt from the catalog: Postgres keeps no CREATE TABLE text. Storage parameters, partitioning and ownership are not included.',
    }
  }

  /**
   * The routines, sequences and triggers of one database, in three statements
   * that run side by side, for the explorer's object lists.
   *
   * The catalog functions print each object the way it was declared, so the
   * definitions are the server's own text rather than anything rebuilt here.
   */
  async function objects({ database } = {}) {
    const databasePool = poolFor(database)

    const [routines, sequences, triggers] = await Promise.all([
      // Aggregates and window functions are left out: they are not something
      // the explorer can show a body for, and pg_get_functiondef throws on
      // them. Routines implemented in C or built into the server have no SQL
      // body worth showing either, and the same function fails on some of
      // them, so it is only asked for what it can print — the CASE keeps the
      // call from ever running on the rest.
      databasePool.query(
        `select n.nspname as "schema",
                p.proname as "name",
                p.prokind as "kind",
                l.lanname as "language",
                pg_get_function_arguments(p.oid) as "args",
                case when p.prokind = 'f' then pg_get_function_result(p.oid) end as "returns",
                case when l.lanname not in ('internal', 'c')
                     then pg_get_functiondef(p.oid) end as "definition"
           from pg_proc p
           join pg_namespace n on n.oid = p.pronamespace
           join pg_language l on l.oid = p.prolang
          where p.prokind in ('f', 'p')
            and n.nspname <> 'information_schema'
            and left(n.nspname, 3) <> 'pg_'
          order by n.nspname, p.proname`,
      ),

      // last_value is null for a sequence nothing has read from yet.
      databasePool.query(
        `select schemaname as "schema",
                sequencename as "name",
                data_type as "dataType",
                last_value as "lastValue"
           from pg_sequences
          where schemaname <> 'information_schema'
            and left(schemaname, 3) <> 'pg_'
          order by schemaname, sequencename`,
      ),

      // Internal triggers are the ones the server makes for itself behind a
      // foreign key or a deferred constraint; nobody wrote them, so nobody
      // is looking for them.
      databasePool.query(
        `select n.nspname as "schema",
                t.tgname as "name",
                c.relname as "table",
                t.tgtype as "tgtype",
                pg_get_triggerdef(t.oid, true) as "definition"
           from pg_trigger t
           join pg_class c on c.oid = t.tgrelid
           join pg_namespace n on n.oid = c.relnamespace
          where not t.tgisinternal
            and n.nspname <> 'information_schema'
            and left(n.nspname, 3) <> 'pg_'
          order by n.nspname, t.tgname`,
      ),
    ])

    return {
      routines: routines.rows.map((row) => ({
        schema: row.schema,
        name: row.name,
        kind: row.kind === 'p' ? 'procedure' : 'function',
        args: row.args,
        returns: row.returns ?? undefined,
        language: row.language,
        definition: row.definition ?? undefined,
      })),
      sequences: sequences.rows.map((row) => ({
        schema: row.schema,
        name: row.name,
        dataType: row.dataType,
        // bigint arrives as a string from pg; see schemaSnapshot.
        lastValue: row.lastValue == null ? null : Number(row.lastValue),
      })),
      triggers: triggers.rows.map((row) => ({
        schema: row.schema,
        name: row.name,
        table: row.table,
        when: triggerTiming(row.tgtype),
        definition: row.definition,
      })),
    }
  }

  function countStatement(node, { where }) {
    return `select count(*) from ${quoteIdent(node.path.schema)}.${quoteIdent(node.path.table)}`
      + (where ? `\nwhere ${where}` : '')
      + ';'
  }

  function previewStatement(node, { limit, offset, order, where }) {
    // `nulls last` in both directions. Descending would otherwise open on a
    // screenful of NULLs — under a LIMIT, that can be the whole first page,
    // which is the one thing nobody sorted a column to see.
    const orderBy = order ? `\norder by ${quoteIdent(order.column)} ${order.dir} nulls last` : ''
    const window = [limit ? `limit ${limit}` : '', offset ? `offset ${offset}` : ''].filter(Boolean)

    return `select *\nfrom ${quoteIdent(node.path.schema)}.${quoteIdent(node.path.table)}`
      + (where ? `\nwhere ${where}` : '')
      + orderBy
      + (window.length ? `\n${window.join(' ')}` : '')
      + ';'
  }

  /**
   * Applies a batch of staged row changes in one transaction.
   *
   * All of it or none of it: a screen of corrections is one intent, and half of
   * it landing is worse than none. Values are bound, never built into the
   * statement — a string that happens to contain a quote is a string.
   */
  async function applyChanges(node, changes, { dryRun } = {}) {
    const built = buildStatements(changes, {
      table: `${quoteIdent(node.path.schema)}.${quoteIdent(node.path.table)}`,
      quoteIdent,
      placeholder: (position) => `$${position}`,
      literal: literalFactory(),
    })

    const script = built.map(({ sql, preview }) => ({ sql, preview }))
    if (dryRun) return { statements: script, applied: 0 }

    const client = await poolFor(node.path.database).connect()
    let applied = 0

    try {
      await client.query('begin')

      for (const [position, statement] of built.entries()) {
        const result = await client.query(statement.sql, statement.params)
        assertOneRow(result.rowCount ?? 0, position)
        applied += 1
      }

      await client.query('commit')
    }
    catch (error) {
      // The rollback's own failure would replace the error that caused it,
      // which is the one worth reporting.
      await client.query('rollback').catch(() => {})
      throw explainQueryError(error, previewOf(built), describePostgresQueryError)
    }
    finally {
      client.release()
    }

    return { statements: script, applied }
  }

  /**
   * Loads batches of rows into a table, in one transaction.
   *
   * Values are bound as text and the server casts them to each column's
   * type, which is how `1`, `true` and `2024-01-01` from a CSV all land
   * right without this side knowing the column types. Postgres allows
   * 65535 parameters per statement, so a batch is split to stay under it.
   */
  async function importRows(node, { columns, batches, truncate, signal }) {
    const table = `${quoteIdent(node.path.schema)}.${quoteIdent(node.path.table)}`
    const names = columns.map(quoteIdent).join(', ')
    const perStatement = Math.max(1, Math.floor(60_000 / Math.max(1, columns.length)))

    const client = await poolFor(node.path.database).connect()
    const processId = client.processID
    const onAbort = () => { cancelBackend(processId).catch(() => {}) }
    signal?.addEventListener('abort', onAbort, { once: true })

    let inserted = 0

    try {
      await client.query('begin')
      if (truncate) await client.query(`truncate table ${table}`)

      for await (const batch of batches) {
        for (let at = 0; at < batch.length; at += perStatement) {
          if (signal?.aborted) throw Object.assign(new Error('Import cancelled.'), { cancelled: true })

          const rows = batch.slice(at, at + perStatement)
          const params = []
          const values = rows
            .map((row) => `(${row.map((value) => `$${params.push(value)}`).join(', ')})`)
            .join(',\n')

          await client.query(`insert into ${table} (${names})\nvalues\n${values}`, params)
          inserted += rows.length
        }
      }

      await client.query('commit')
    }
    catch (error) {
      await client.query('rollback').catch(() => {})
      if (error?.cancelled) throw error
      if (error?.code === '57014') throw Object.assign(new Error('Import cancelled.'), { cancelled: true })
      throw explainQueryError(error, `insert into ${table} (${names}) values (…)`, describePostgresQueryError)
    }
    finally {
      signal?.removeEventListener('abort', onAbort)
      client.release()
    }

    return { inserted }
  }

  return {
    serverVersion: String(versionResult.rows[0].version).split(' ').slice(0, 2).join(' '),
    defaultDatabase: versionResult.rows[0].db,
    query,
    beginTransaction,
    listChildren,
    schemaSnapshot,
    previewStatement,
    countStatement,
    structure,
    objects,
    applyChanges,
    importRows,
    ddlStatements: (node, operation) => buildDdlStatements('postgres', quoteIdent, node, operation),
    close: closeAll,
  }
}

export default {
  meta: {
    id: 'postgres',
    label: 'PostgreSQL',
    target: 'server',
    defaultPort: 5432,
    badge: 'PG',
    color: '#4d94c8',
    levels: ['database', 'schema'],
    quote: '"',
    engine: 'postgres',
    capabilities: { alterColumn: true, comments: true, dump: 'pg_dump', restore: 'psql' },
  },
  open,
}
